### PR TITLE
Initial release

### PR DESCRIPTION
**Pull request by haltcase**

### CODE REVIEW

**Comment by rattrayalex** [comment]
@citycide do you think there's any chance we could add a previous commit with the "starting point" and then a second commit with all changes? Might be a bit of a pain so no worries if so. 

For that matter, what is it based on?

**Comment by haltcase** [comment]
> do you think there's any chance we could add a previous commit with the "starting point" and then a second commit with all changes? Might be a bit of a pain so no worries if so.

Not sure what you mean here.

> what is it based on?

It was mostly generated by the VS Code extension generator using `lightscript-sublime` as a base.

**Comment by rattrayalex** [comment]
ah, gotcha. were there hand-edits?

**Comment by rattrayalex** [comment]
if so, can you separate out the hand-edits as a separate commit?

**Comment by haltcase** [comment]
Only to metadata, not to the `.tmLanguage`, yet at least.

**Comment by rattrayalex** [comment]
oh, okay. so if we were to just re-run the generation command it wouldn't break anything?

**Comment by haltcase** [comment]
Yeah pretty sure it would be fine.

**Comment by rattrayalex** [comment]
Awesome! Gonna try to deploy now...

**Pull request merged**
